### ISSUE TITLE
Test 0120 (Media Overlays Reflowable Tests): mo-nav-030 assumes pagination

### ISSUE THREAD

**Issue by pettarin** [IDPF/epub-testsuite#73]
Current:

> Let media overlay playback continue while you turn pages. The playback should be updated to reflect your current position.

Comment: This test assumes that the Reading System paginates (or, it offers an option for...) the reflowable contents. Should this test consider scrolling layout as well? In both cases, the test passes when the MO playback follows user actions (turning pages or scrolling the text column)? Is creating a new test for scrolling layout more appropriate? What if the Reading System allows the user to link/unlink the MO from the text navigation (within the same XHTML document)?

**Comment by danielweck** [comment]
About the scrolling view: Readium offers a choice to integrators/vendors (via a configuration parameter) between: automatically adjusting the playback position after a scroll event (user-driven interaction) so that the audio is always in sync with the visible portion of the HTML document, or letting the playback continue irrespective of the new scrolled viewport position (in which case the pause-play commands can be used to restore the visibility of the resumed / playing element).
I know of at least one vendor who decided to use the latter option, based on user experience feedback (their target user base may have specific requirements though, not necessarilly representative of a mainstream audience).

**Comment by pettarin** [comment]
Thank you. My impression is that your comment seems to confirm that this test (mo-nav-030) might be split/better specified.

**Comment by marisademeglio** [comment]
Would it be sufficient to say "Let media overlay playback continue while you turn pages or scroll (whichever applies to your reading system). The playback should be updated to reflect your current position."

It's hard to accommodate the latter case described above by Daniel since it's hard to know what vendors intended. Even if we split the test into scrolling vs paginated, there would still be potential ambiguity for the case of scrolling.
